"""Per-venue scrapers.

Each scraper lives in ``foghorn.scrapers.<venue_slug>`` and exposes a
zero-argument ``scrape() -> list[ScrapedShow]``. ``REGISTERED_SCRAPERS`` maps a
venue slug to its scrape callable; the ``make scrape`` CLI
(``foghorn.cli.scrape``) iterates it, runs each through the ingest pipeline, and
prints per-venue counts.

Adding a venue: implement ``foghorn/scrapers/<slug>.py`` with a ``scrape()``
(see ``bird_and_beckett`` for the pattern — fetch is isolated from a pure,
fixture-testable parse), then add an entry here.
"""

from __future__ import annotations

from collections.abc import Callable

from foghorn.models import ScrapedShow
from foghorn.scrapers import (
    august_hall,
    bimbos_365,
    bird_and_beckett,
    black_cat,
    boom_boom_room,
    bottom_of_the_hill,
    cafe_du_nord,
    cal_performances,
    california_jazz_conservatory,
    center_for_new_music,
    chez_hanny,
    club_deluxe,
    club_fox,
    cornerstone_berkeley,
    dna_lounge,
    dresher_ensemble_studio,
    felton_music_hall,
    fox_theater_oakland,
    gilman_924,
    gray_area,
    great_american_music_hall,
    greek_theatre_berkeley,
    guild_theatre,
    indexical,
    ivy_room,
    keys_jazz_bistro,
    kilowatt,
    kuumbwa_jazz_center,
    little_hill_lounge,
    little_lous_bbq,
    madrone_art_bar,
    make_out_room,
    medicine_for_nightmares,
    meyhouse_jazz,
    mills_littlefield,
    moes_alley,
    mr_tipples,
    mystic_theatre,
    natural_grocery_annex,
    neck_of_the_woods,
    noontime_concerts,
    ocean_ale_house,
    old_first_concerts,
    paramount_theatre_oakland,
    piedmont_piano,
    pier_23_cafe,
    poor_house_bistro,
    regency_ballroom,
    rickshaw_stop,
    sjz_break_room,
    smileys_saloon,
    stanford_jazz_workshop,
    sweetwater_music_hall,
    the_back_room,
    the_catalyst,
    the_chapel,
    the_crepe_place,
    the_dawn_club,
    the_fillmore,
    the_independent,
    the_knockout,
    the_lab,
    the_lost_church,
    the_ritz,
    the_sound_room,
    the_warfield,
    thee_stork_club,
    toms_place,
    uc_theatre,
    uptown_theatre_napa,
    wyldflowr_arts,
    yoshis,
)

REGISTERED_SCRAPERS: dict[str, Callable[[], list[ScrapedShow]]] = {
    regency_ballroom.VENUE_SLUG: regency_ballroom.scrape,
    the_fillmore.VENUE_SLUG: the_fillmore.scrape,
    the_ritz.VENUE_SLUG: the_ritz.scrape,
    sjz_break_room.VENUE_SLUG: sjz_break_room.scrape,
    sweetwater_music_hall.VENUE_SLUG: sweetwater_music_hall.scrape,
    mystic_theatre.VENUE_SLUG: mystic_theatre.scrape,
    club_fox.VENUE_SLUG: club_fox.scrape,
    club_deluxe.VENUE_SLUG: club_deluxe.scrape,
    uc_theatre.VENUE_SLUG: uc_theatre.scrape,
    thee_stork_club.VENUE_SLUG: thee_stork_club.scrape,
    the_warfield.VENUE_SLUG: the_warfield.scrape,
    neck_of_the_woods.VENUE_SLUG: neck_of_the_woods.scrape,
    bimbos_365.VENUE_SLUG: bimbos_365.scrape,
    august_hall.VENUE_SLUG: august_hall.scrape,
    bird_and_beckett.VENUE_SLUG: bird_and_beckett.scrape,
    black_cat.VENUE_SLUG: black_cat.scrape,
    boom_boom_room.VENUE_SLUG: boom_boom_room.scrape,
    bottom_of_the_hill.VENUE_SLUG: bottom_of_the_hill.scrape,
    cafe_du_nord.VENUE_SLUG: cafe_du_nord.scrape,
    california_jazz_conservatory.VENUE_SLUG: california_jazz_conservatory.scrape,
    center_for_new_music.VENUE_SLUG: center_for_new_music.scrape,
    cornerstone_berkeley.VENUE_SLUG: cornerstone_berkeley.scrape,
    dna_lounge.VENUE_SLUG: dna_lounge.scrape,
    fox_theater_oakland.VENUE_SLUG: fox_theater_oakland.scrape,
    gilman_924.VENUE_SLUG: gilman_924.scrape,
    greek_theatre_berkeley.VENUE_SLUG: greek_theatre_berkeley.scrape,
    great_american_music_hall.VENUE_SLUG: great_american_music_hall.scrape,
    guild_theatre.VENUE_SLUG: guild_theatre.scrape,
    ivy_room.VENUE_SLUG: ivy_room.scrape,
    keys_jazz_bistro.VENUE_SLUG: keys_jazz_bistro.scrape,
    kilowatt.VENUE_SLUG: kilowatt.scrape,
    madrone_art_bar.VENUE_SLUG: madrone_art_bar.scrape,
    medicine_for_nightmares.VENUE_SLUG: medicine_for_nightmares.scrape,
    mr_tipples.VENUE_SLUG: mr_tipples.scrape,
    natural_grocery_annex.VENUE_SLUG: natural_grocery_annex.scrape,
    ocean_ale_house.VENUE_SLUG: ocean_ale_house.scrape,
    piedmont_piano.VENUE_SLUG: piedmont_piano.scrape,
    rickshaw_stop.VENUE_SLUG: rickshaw_stop.scrape,
    the_back_room.VENUE_SLUG: the_back_room.scrape,
    the_chapel.VENUE_SLUG: the_chapel.scrape,
    the_independent.VENUE_SLUG: the_independent.scrape,
    the_knockout.VENUE_SLUG: the_knockout.scrape,
    dresher_ensemble_studio.VENUE_SLUG: dresher_ensemble_studio.scrape,
    kuumbwa_jazz_center.VENUE_SLUG: kuumbwa_jazz_center.scrape,
    little_hill_lounge.VENUE_SLUG: little_hill_lounge.scrape,
    indexical.VENUE_SLUG: indexical.scrape,
    make_out_room.VENUE_SLUG: make_out_room.scrape,
    meyhouse_jazz.VENUE_SLUG: meyhouse_jazz.scrape,
    poor_house_bistro.VENUE_SLUG: poor_house_bistro.scrape,
    chez_hanny.VENUE_SLUG: chez_hanny.scrape,
    pier_23_cafe.VENUE_SLUG: pier_23_cafe.scrape,
    the_dawn_club.VENUE_SLUG: the_dawn_club.scrape,
    the_sound_room.VENUE_SLUG: the_sound_room.scrape,
    toms_place.VENUE_SLUG: toms_place.scrape,
    uptown_theatre_napa.VENUE_SLUG: uptown_theatre_napa.scrape,
    gray_area.VENUE_SLUG: gray_area.scrape,
    mills_littlefield.VENUE_SLUG: mills_littlefield.scrape,
    the_lab.VENUE_SLUG: the_lab.scrape,
    wyldflowr_arts.VENUE_SLUG: wyldflowr_arts.scrape,
    yoshis.VENUE_SLUG: yoshis.scrape,
    cal_performances.VENUE_SLUG: cal_performances.scrape,
    felton_music_hall.VENUE_SLUG: felton_music_hall.scrape,
    little_lous_bbq.VENUE_SLUG: little_lous_bbq.scrape,
    moes_alley.VENUE_SLUG: moes_alley.scrape,
    old_first_concerts.VENUE_SLUG: old_first_concerts.scrape,
    paramount_theatre_oakland.VENUE_SLUG: paramount_theatre_oakland.scrape,
    smileys_saloon.VENUE_SLUG: smileys_saloon.scrape,
    the_catalyst.VENUE_SLUG: the_catalyst.scrape,
    the_crepe_place.VENUE_SLUG: the_crepe_place.scrape,
    the_lost_church.VENUE_SLUG: the_lost_church.scrape,
    stanford_jazz_workshop.VENUE_SLUG: stanford_jazz_workshop.scrape,
    noontime_concerts.VENUE_SLUG: noontime_concerts.scrape,
}
